SELECT ID, VISIT_DATE, PEOPLE
FROM (
    SELECT
        *,
        LEAD(people) OVER(ORDER BY ID) NEXT_PEOPLE,
        LEAD(people, 2) OVER(ORDER BY ID) NEXT_PEOPLE2,
        LAG(people) OVER(ORDER BY ID) PREV_PEOPLE,
        LAG(people, 2) OVER(ORDER BY ID) PREV_PEOPLE2
    FROM stadium
) TBL1
WHERE PEOPLE >= 100 AND (
    (NEXT_PEOPLE >= 100 AND NEXT_PEOPLE2 >= 100) OR 
    (PREV_PEOPLE >= 100 AND PREV_PEOPLE2 >= 100) OR 
    (NEXT_PEOPLE >= 100 AND PREV_PEOPLE >= 100)
)